# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/macro
    id: macro
    binary: macro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - id: macro
    ids:
      - macro
    formats: [tar.gz]
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - none*
    format_overrides:
      - goos: windows
        formats: [zip]

report_sizes: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
