package module

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/railzwaylabs/macro/internal/fsutil"
	"github.com/railzwaylabs/macro/internal/project"
)

//go:embed templates
var templates embed.FS

var ErrAlreadyExists = errors.New("module already exists")

type Result struct {
	Directory     string
	MigrationUp   string
	MigrationDown string
}

type Plan struct {
	Directory     string
	CreateFiles   []string
	UpdateFiles   []string
	manifest      project.Manifest
	migrationUp   string
	migrationDown string
	modulePath    string
}

const generatedRegistryHeader = "// Code generated by Macro. DO NOT EDIT."

func BuildPlan(projectDirectory, name string, timestamp time.Time) (Plan, error) {
	if err := project.ValidateName(name); err != nil {
		return Plan{}, fmt.Errorf("invalid module name: %w", err)
	}

	manifest, err := project.Read(projectDirectory)
	if err != nil {
		return Plan{}, err
	}

	if _, exists := manifest.Modules[name]; exists {
		return Plan{}, fmt.Errorf("module %q already exists in %s: choose another module name or remove the existing module first: %w", name, project.ManifestName, ErrAlreadyExists)
	}

	destination := filepath.Join(projectDirectory, "internal", name)
	if err := ensureDestinationAvailable(destination); err != nil {
		return Plan{}, err
	}

	migrationName := normalizeMigrationName(name)
	prefix := timestamp.UTC().Format("20060102150405")
	migrationDirectory := filepath.Join(projectDirectory, "migrations")
	up := filepath.Join(migrationDirectory, prefix+"_"+migrationName+".up.sql")
	down := filepath.Join(migrationDirectory, prefix+"_"+migrationName+".down.sql")
	modulePath, err := readModulePath(projectDirectory)
	if err != nil {
		return Plan{}, err
	}
	registryPath := filepath.Join(projectDirectory, "internal", "modules", "modules.go")
	updates := []string{filepath.Join(projectDirectory, project.ManifestName)}
	if contents, err := os.ReadFile(registryPath); err == nil {
		if !strings.HasPrefix(string(contents), generatedRegistryHeader) {
			return Plan{}, fmt.Errorf("refuse to overwrite developer-owned module registry %s", registryPath)
		}
		updates = append(updates, registryPath)
	} else if !errors.Is(err, os.ErrNotExist) {
		return Plan{}, fmt.Errorf("inspect generated module registry: %w", err)
	}
	return Plan{
		Directory: destination,
		CreateFiles: []string{
			filepath.Join(destination, "module.go"),
			filepath.Join(destination, "application", "service.go"),
			filepath.Join(destination, "transport", "grpc", "handler.go"), up, down,
		},
		UpdateFiles: updates,
		manifest:    manifest, migrationUp: up, migrationDown: down,
		modulePath: modulePath,
	}, nil
}

func Add(projectDirectory, name string) (Result, error) {
	return add(projectDirectory, name, time.Now().UTC())
}

func add(projectDirectory, name string, timestamp time.Time) (generated Result, returnErr error) {
	plan, err := BuildPlan(projectDirectory, name, timestamp)
	if err != nil {
		return Result{}, err
	}
	manifest := plan.manifest
	destination := plan.Directory
	if err := os.MkdirAll(destination, 0o755); err != nil {
		return Result{}, fmt.Errorf("create module directory %s: %w", destination, err)
	}

	migrationName := normalizeMigrationName(name)
	migrationDirectory := filepath.Join(projectDirectory, "migrations")
	generated = Result{
		Directory:     destination,
		MigrationUp:   plan.migrationUp,
		MigrationDown: plan.migrationDown,
	}
	registryPath := filepath.Join(projectDirectory, "internal", "modules", "modules.go")
	registryBefore, registryErr := os.ReadFile(registryPath)
	hasRegistry := registryErr == nil
	defer func() {
		if returnErr == nil {
			return
		}
		for _, path := range []string{destination, generated.MigrationUp, generated.MigrationDown} {
			if cleanupErr := os.RemoveAll(path); cleanupErr != nil {
				returnErr = errors.Join(returnErr, fmt.Errorf("remove incomplete scaffold %s: %w", path, cleanupErr))
			}
		}
		if hasRegistry {
			if cleanupErr := fsutil.WriteFileAtomic(registryPath, registryBefore, 0o644); cleanupErr != nil {
				returnErr = errors.Join(returnErr, fmt.Errorf("restore module registry: %w", cleanupErr))
			}
		}
	}()

	data := templateData{Name: name, ModulePath: plan.modulePath, PackageName: normalizePackageName(name)}
	for _, file := range []struct{ source, target string }{
		{"templates/module.go.tmpl", filepath.Join(destination, "module.go")},
		{"templates/service.go.tmpl", filepath.Join(destination, "application", "service.go")},
		{"templates/handler.go.tmpl", filepath.Join(destination, "transport", "grpc", "handler.go")},
	} {
		if err := render(file.source, file.target, data); err != nil {
			return generated, err
		}
	}
	if err := os.MkdirAll(migrationDirectory, 0o755); err != nil {
		return generated, fmt.Errorf("create migrations directory: %w", err)
	}
	migrationData := map[string]string{"Name": migrationName}
	if err := render("templates/migration.up.sql.tmpl", generated.MigrationUp, migrationData); err != nil {
		return generated, err
	}
	if err := render("templates/migration.down.sql.tmpl", generated.MigrationDown, migrationData); err != nil {
		return generated, err
	}

	if manifest.Modules == nil {
		manifest.Modules = make(map[string]project.Module)
	}
	manifest.Modules[name] = project.Module{}
	if hasRegistry {
		if err := renderRegistry(registryPath, plan.modulePath, manifest.Modules); err != nil {
			return generated, err
		}
	}
	if err := project.Write(filepath.Join(projectDirectory, project.ManifestName), manifest); err != nil {
		return generated, fmt.Errorf("register module %q: %w", name, err)
	}
	return generated, nil
}

type templateData struct {
	Name        string
	ModulePath  string
	PackageName string
}

type registryModule struct {
	Name  string
	Alias string
}

func renderRegistry(path, modulePath string, registered map[string]project.Module) error {
	names := make([]string, 0, len(registered))
	for name := range registered {
		names = append(names, name)
	}
	sort.Strings(names)
	modules := make([]registryModule, 0, len(names))
	for _, name := range names {
		alias := normalizePackageName(name)
		for _, existing := range modules {
			if existing.Alias == alias {
				return fmt.Errorf("module names %q and %q normalize to the same Go package alias %q", existing.Name, name, alias)
			}
		}
		modules = append(modules, registryModule{Name: name, Alias: alias})
	}
	return render("templates/registry.go.tmpl", path, struct {
		ModulePath string
		Modules    []registryModule
	}{modulePath, modules})
}

func readModulePath(directory string) (string, error) {
	contents, err := os.ReadFile(filepath.Join(directory, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("read Go module path: %w", err)
	}
	fields := strings.Fields(string(contents))
	if len(fields) < 2 || fields[0] != "module" {
		return "", fmt.Errorf("read Go module path: go.mod must start with a module directive")
	}
	return fields[1], nil
}

func normalizePackageName(name string) string {
	value := strings.ReplaceAll(normalizeMigrationName(name), "_", "")
	if value == "" || value[0] >= '0' && value[0] <= '9' {
		value = "module" + value
	}
	if token.IsKeyword(value) {
		value += "module"
	}
	return value
}

func render(source, target string, data any) error {
	parsed, err := template.ParseFS(templates, source)
	if err != nil {
		return fmt.Errorf("parse %s: %w", source, err)
	}
	var output bytes.Buffer
	if err := parsed.Execute(&output, data); err != nil {
		return fmt.Errorf("render %s: %w", source, err)
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", target, err)
	}
	if err := fsutil.WriteFileAtomic(target, output.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}
	return nil
}

func ensureDestinationAvailable(destination string) error {
	if _, err := os.Stat(destination); err == nil {
		return fmt.Errorf("module directory %s: %w", destination, ErrAlreadyExists)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect module directory %s: %w", destination, err)
	}
	return nil
}

func normalizeMigrationName(name string) string {
	var result strings.Builder
	previousUnderscore := false
	for _, character := range strings.ToLower(name) {
		if character >= 'a' && character <= 'z' || character >= '0' && character <= '9' {
			result.WriteRune(character)
			previousUnderscore = false
		} else if !previousUnderscore && result.Len() > 0 {
			result.WriteByte('_')
			previousUnderscore = true
		}
	}
	return strings.Trim(result.String(), "_")
}
